const express = require('express');
const authMiddleware = require('../middleware/auth');
const { AdminApprovalController, getPendingAdminsController, getApprovedAdminsController, getRejectedAdminsController, getAllAdminsController, getAdminController, getDashboardStatsController } = require('../controller/superAdminApprovalController');
const { showDashboardController, showDashboardOfCourseController, addSectionsController, updateInchargeController, showSubjectController, deleteSubjectController, addSubjectController, deleteSectionController, deleteCourseController, deleteSemesterController, addSemesterController, addCourseController } = require('../controller/courseController');
const { getGroupsController, createGroupController, deleteGroupController } = require('../controller/subjectGroupController');
const SuperAdminApprovalRouter = express.Router();

SuperAdminApprovalRouter.put('/admin/:user_id/approve', authMiddleware(['super_admin']), AdminApprovalController);
SuperAdminApprovalRouter.get('/pendingAdmin', authMiddleware(['super_admin']), getPendingAdminsController);
SuperAdminApprovalRouter.get('/approvedAdmin', authMiddleware(['super_admin']), getApprovedAdminsController);
SuperAdminApprovalRouter.get('/rejectedAdmin', authMiddleware(['super_admin']), getRejectedAdminsController);
SuperAdminApprovalRouter.get('/allAdmin', authMiddleware(['super_admin']), getAllAdminsController);
SuperAdminApprovalRouter.get('/admin/:user_id', authMiddleware(['super_admin', 'admin']), getAdminController);
SuperAdminApprovalRouter.get('/courseDashboard', authMiddleware(['super_admin']), showDashboardController);
SuperAdminApprovalRouter.get('/courseDashboard/:course_id', authMiddleware(['super_admin']), showDashboardOfCourseController);
SuperAdminApprovalRouter.post('/addSection/:course_id', authMiddleware(['super_admin']), addSectionsController);
SuperAdminApprovalRouter.put('/updateIncharge/:course_id', authMiddleware(['super_admin']), updateInchargeController);
SuperAdminApprovalRouter.get('/subjects/:course_id/:semester_number', authMiddleware(['super_admin']), showSubjectController);
SuperAdminApprovalRouter.delete('/deleteSubject/:course_id/:semester_number/:subject_id', authMiddleware(['super_admin']), deleteSubjectController);
SuperAdminApprovalRouter.post('/addSubject/:course_id/:semester_number', authMiddleware(['super_admin']), addSubjectController);
SuperAdminApprovalRouter.delete('/deleteSection/:course_id/:section_id', authMiddleware(['super_admin']), deleteSectionController);
SuperAdminApprovalRouter.delete('/deleteCourse/:course_id', authMiddleware(['super_admin']), deleteCourseController);
SuperAdminApprovalRouter.delete('/deleteSemester/:course_id/:semester_number', authMiddleware(['super_admin']), deleteSemesterController);
SuperAdminApprovalRouter.post('/addSemester/:course_id', authMiddleware(['super_admin']), addSemesterController);
SuperAdminApprovalRouter.post('/addCourse', authMiddleware(['super_admin']), addCourseController);
SuperAdminApprovalRouter.get('/dashboardStats', authMiddleware(['super_admin']), getDashboardStatsController);
SuperAdminApprovalRouter.get('/subject-groups', authMiddleware(['super_admin']), getGroupsController);
SuperAdminApprovalRouter.post('/subject-groups', authMiddleware(['super_admin']), createGroupController);
SuperAdminApprovalRouter.delete('/subject-groups/:group_id', authMiddleware(['super_admin']), deleteGroupController);

module.exports = SuperAdminApprovalRouter;